# Generated by Django 4.0 on 2022-02-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime_in',
            new_name='datetime_com',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datetime_in',
            new_name='datetime_post',
        ),
    ]
